### ISSUE TITLE
Ошибка в настройках модуля "Модуль 'CSalePaySystem' не определен"

### ISSUE THREAD

**Issue by Potalius** [Komtet/komtet-kassa-bitrix#3]
https://github.com/Komtet/komtet-kassa-bitrix/blob/ad1ed50e5a5aa383db332f67cd6cb970d7cd72db/komtet.kassa/options.php#L12

Также нужно подключать еще и модуль 'sale', потому-что в настройках есть обращение к CSalePaySystem который находится в этом модуле.

`Loader::includeModule('sale');`

**Comment by mini4** [comment]
исправлено
