### ISSUE TITLE
Class 'CSalePaySystem' not found (0)

### ISSUE THREAD

**Issue by raspberry367** [Komtet/komtet-kassa-bitrix#8]
Не находит класс не смотря на то, что модуль 'sale' подключен

[Error] 
Class 'CSalePaySystem' not found (0)
/var/www/html/bitrix/modules/komtet.kassa/options.php:139
#0: include
	/var/www/html/bitrix/modules/main/admin/settings.php:64
#1: require_once(string)
	/var/www/html/bitrix/admin/settings.php:2

**Comment by spectacular1723** [comment]
Класс CSalePaySystem (доступен с 3.3.6, устарел с 16.0.2)
https://dev.1c-bitrix.ru/api_help/sale/classes/csalepaysystem/index.php
в 1С - Битрикс есть галка "Включить обработку устаревших событий" модуля sale, что позволит настроить взаимодействие с устаревшими классами, событиями. Поставьте её.
Так же, опишите, пожалуйста, проблему более детально, с указанием Вашей версии 1С - Битрикс на адрес эл. почты kassa@komtet.ru , если выше изложенная рекомендация не поможет.

**Comment by raspberry367** [comment]
Проблема решена
